name: Development Environment

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      VERSION: ${{github.sha}}
      CONTAINER_REGISTRY: ${{secrets.CONTAINER_REGISTRY}}
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}


    steps:
      - uses: actions/checkout@v2


      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: asia.gcr.io
          image: amralaayassen/ephemeral-envs-gateway
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_latest: true
          tag: $VERSION
          path: ./gateway
          build_file: Dockerfile
          debug: true
      
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods

      
     
