name: Development Environment

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: self-hosted
    timeout-minutes: 5

    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.DOCKER_USERNAME }}
      REGISTRY_PW: ${{ secrets.DOCKER_PASSWORD  }}
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: ./scripts/build-image.sh gateway

      - name: Publish
        run: ./scripts/push-image.sh gateway

      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods

      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "tenant.yaml"
          FILE_DATA: "
          apiVersion: capsule.clastix.io/v1beta2
          kind: Tenant
          metadata:
            name: dev
          spec:
            owners:
            - name: amralaayassen
              kind: User
          "
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with: 
          args: |
            create -f tenant.yaml
            
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with: 
          args: |
            get tenants
           
