name: Development Environment

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: self-hosted
    timeout-minutes: 5

    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}
    steps:
      - uses: actions/checkout@v2

      # - name: Kaniko build
      #   uses: aevea/action-kaniko@master
      #   with:
      #     image: amralaayassen/ephemeral-envs-gateway
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     tag_with_latest: true
      #     tag: ${{github.sha}}
      #     path: ./gateway
      #     build_file: Dockerfile
      #     debug: true
      - name: Build
        run: ./scripts/build-image.sh gateway

      #
      # Publishes the Docker image to the container registry.
      #
      - name: Publish
        run: ./scripts/push-image.sh gateway
      # - name: Log in to Red Hat Registry
      #   uses: redhat-actions/podman-login@v1
      #   with:
      #     registry: registry-1.docker.io
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Buildah Action
      #   uses: redhat-actions/buildah-build@v2
      #   with:
      #     image: amralaayassen/ephemeral-envs-gateway
      #     tags: ${{ github.sha }}
      #     containerfiles: |
      #       ./gateway/Dockerfile

      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods
