name: Development Environment

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: self-hosted
    timeout-minutes: 5

    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.DOCKER_USERNAME }}
      REGISTRY_PW: ${{ secrets.DOCKER_PASSWORD  }}
      ACTOR: ${{ github.actor}}
    steps:
      - uses: actions/checkout@v2
        name: checkout

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build
      #   run: ./scripts/build-image.sh gateway

      # - name: Publish
      #   run: ./scripts/push-image.sh gateway

      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: 18

      # - name: Install dependencies
      #   run: npm install

      # - uses: actions-hub/kubectl@master
      #   env:
      #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      #   with:
      #     args: get pods
      - name: Show GitHub context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
      - name: install YQ
        run: sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

      - name: github actor
        run: echo ${{env.ACTOR}}

      - name: update tenant name
        run: |
          name="gateway-${{env.ACTOR}}-${{env.VERSION}}" \
          name= ${name,}
          yq e -i '.metadata.name = "$name"' tenant.yaml

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: |
            create -f tenant.yaml

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: |
            get tenants
