#
# GitHub Actions workflow.
#
# Deploys the MongoDB database.
#

name: Deploy MongoDB

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: self-hosted
    timeout-minutes: 5

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2

      #
      # Install Kubectl and connect.
      #
      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      #
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods

      #
      # Deploys the MongoDB database to Kubernetes.
      #
     
