name: Test connection

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: self-hosted
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      #
      # Install Kubectl and connect.
      #
      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      #
      - name: Set up kubeconfig
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo "$KUBECONFIG" > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml

      #
      # Deploys the MongoDB database to Kubernetes.
      #
      - name: Deploy
        run: kubectl get pods
