name: Development Environment

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: self-hosted
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods

      
     
